global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    # atur nama network untuk dikelola traefik
    network: proxy

  # custom jika ada provider selain docker, misal apache/nginx
  # file:
  #   directory: /etc/traefik/configs/
  #   watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: your.name@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
